### PR TITLE
Fix a dead player could vote issue

### LINKED ISSUE #161: Prevent players from voting against others that are dead
**Describe the bug**
Currently, the client allows players to vote for others that are dead.
Additionally, dead players can vote.

**To Reproduce**
1. Mafia kills someone
2. When the day discussion starts, player is still able to vote for the player who has been killed.

**Expected behavior**
The player circles of players that are dead should not be clickable.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**

### Issue Approval:
- [x]  Issue approved by: @SiyuQian

### PR DESCRIPTION
**Pull request by SiyuQian**
# Description
This PR fixes #161 

Force the system to think that a dead player always having a voted status. In this way, we don't have to write up extra logic to fix the issue. (I think a unique CSS would be applied to the dead players in the new pull request so the users would be confused)

# Type of change:
* Bug fix (Non-breaking change which fixes a bug)

### CODE REVIEW

**Review by jteo97 — APPROVED** [review]
Well done on the nice and simple bug fix.

File: frontend/src/Components/Player.jsx [hunk 1]
```diff
@@ -18,9 +18,8 @@ export default function Player({ playerId, playerName, style, childRef }) {
     const playerStyle = classNames({
         [styles.playerWrapper]: true,
         [styles.isHoverable]: isHoverable,
-        [styles.hasVoted]: hasVoted,
+        [styles.hasVoted]: isDead ? isDead : hasVoted,
```
Comment (ateagit) [inline frontend/src/Components/Player.jsx:21]: This dosent seem to fix the issue for me? The hasVoted clasName is purely cosmetic (it puts a red dot next to the player) and dosent prevent a player from voting. The `isDead` boolean refers to the current player that you are clicking on (not you). To fix this, you have to check alivePlayers to see if your nickname is present. 

```
    const { state: generalState } = useContext(GeneralContext);
    const amIDead = gameState.alivePlayers.includes(generalState.nickname)
```
(This doesn't really look that clean so it may be better isDead as part of the game state)

**Review by ateagit — CHANGES_REQUESTED** [review]

File: frontend/src/Components/Player.jsx (hunk 1 above)
Comment (reeved) [reply frontend/src/Components/Player.jsx:21]: Agreed. We need a solution that prevents the dead user from being able to click other players. Otherwise the server will still receive vote information.

Comment (SiyuQian) [reply frontend/src/Components/Player.jsx:21]: @ateagit The solution does not work because "hasVoted" variable didn't do the job properly? Don't you think if one person is voted then he would not be able to vote again? So we should create another ticket to fix the hasVoted logic.

Comment (ateagit) [reply frontend/src/Components/Player.jsx:21]: This is up to the team. I'm ok with players being able to change their vote as long as it's before the night ends (with an exception being the detective). The `hasVoted` variable simply tells you if the current player object being rendered is in the `playersWhoVoted` list, it does not tell you if you (your player object) has voted. In other words, its only job is to add styling if that player has voted for another player during the vote phase. To check if you (the current player) has voted, you have to check if the `gameState.votingState.vote` variable is set (meaning that you have voted for someone). Always setting that for dead people dosent seem like a good workaround to prevent people from voting.

Comment (reeved) [reply frontend/src/Components/Player.jsx:21]: > This is up to the team. I'm ok with players being able to change their vote as long as it's before the night ends (with an exception being the detective).

I agree with this behaviour! Unless we implement a "vote confirm" button, we should let players change their votes until the time runs out. Especially, after testing #198, I thought it was quite cool being able to click different players and seeing who I was voting for :)

Comment (SiyuQian) [reply frontend/src/Components/Player.jsx:21]: @ateagit @reeved So after implementing that, then we would put the dead users into the votedConfirmed group. From my perspective, every program should follow the DRY rule. If implement the 'cannot vote' logic twice, it will make the program WET.

Comment (reeved) [reply frontend/src/Components/Player.jsx:21]: Yeah thats one solution. But the game has no "vote confirm" logic implemented in the front/backend, just a map for the current voting session that stores who has voted, and who they voted for. If we want to add vote confirm logic, then you would need to talk to the Backend team too because this would require additional work form both teams.

I think Alan's original suggestion was to use the ClickValidation that's already present in the Player Component. But do another check for `amIDead` which checks if the Player is alive or not. There is also an `isDead` but that is used purely for styling purposes for each Player rendered through the Table component.

This way, a dead player will not be able to click any other players AT ALL. So we wouldn't have to worry about them having the voted symbol.

Comment (SiyuQian) [reply frontend/src/Components/Player.jsx:21]: @reeved  so what about the "Another reason that I think we should change the votedConfirmed logic is that not only dead players cant vote but also a voted confirmed player. Correct? So the logic should be implemented for the votedConfirmed status instead of a dead player?" section. lol

Comment (jteo97) [reply frontend/src/Components/Player.jsx:21]: Preferably lets not create another vote confirm logic this late. Have we still not agreed on a solution to this issue? I thought its just check if player is dead and if so don't render the hover thing over other players and if in the case they do click don't send vote message across.

**Comment by SiyuQian** [comment]
@reeved @ateagit @jteo97 Yo team. Thanks for all the suggestions. The implementation has been done.

File: frontend/src/Components/Player.jsx [hunk 2]
```diff
@@ -20,7 +20,6 @@ export default function Player({ playerId, playerName, style, childRef }) {
         [styles.isHoverable]: isHoverable,
         [styles.hasVoted]: hasVoted,
         [styles.isClicked]: isClicked,
-        [styles.isDead]: isDead,
```
Comment (reeved) [inline frontend/src/Components/Player.jsx:23]: We still need these line to style dead players right?

File: frontend/src/Hooks/useGameState.js [hunk 3]
```diff
@@ -211,12 +211,21 @@ export default function useGameState() {
         }
 
         function onDayStart({ timeToVote }) {
-            dispatch({
-                type: 'day-start',
-                status: 'Select someone to be on trial',
-                votablePlayers: state.alivePlayers.filter((p) => p !== generalState.nickname),
-                timeToVote,
-            });
+            const amIDead = !state.alivePlayers.includes(generalState.nickname);
```
Comment (reeved) [inline frontend/src/Hooks/useGameState.js:214]: Can we make amIdead another state value too? That way we can check for if you're dead easily in other components too e.g. I would like to hide my abstain vote button if dead.

Also would this only prevent players from voting during the day? Seems like it could allow people to still vote during the night and during a trial.... But this is just from me reading code

**Review by reeved — DISMISSED** [review]

File: frontend/src/Components/Player.jsx (hunk 2 above)
Comment (SiyuQian) [reply frontend/src/Components/Player.jsx:23]: Yes. Indeed. I believe I accidentally removed this line of code ...

File: frontend/src/Hooks/useGameState.js (hunk 3 above)
Comment (SiyuQian) [reply frontend/src/Hooks/useGameState.js:214]: @reeved Right.. Looks like it. I am not that familiar with the mafia game.. haha .. We do have another version but it does not have a trial stage.. lol.. going to fix that real quick

**Review by Dhors — APPROVED** [review]
Nice changes!
