### PR TITLE
Fix/deadplayers cant use abilities

### LINKED ISSUE #161: Prevent players from voting against others that are dead
**Describe the bug**
Currently, the client allows players to vote for others that are dead.
Additionally, dead players can vote.

**To Reproduce**
1. Mafia kills someone
2. When the day discussion starts, player is still able to vote for the player who has been killed.

**Expected behavior**
The player circles of players that are dead should not be clickable.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**

### Issue Approval:
- [x]  Issue approved by: @SiyuQian

### PR DESCRIPTION
**Pull request by Dhors**
# Description
This PR fixes #161

added logic to make it so that during the night dead players cannot click on any players, while showing a status message that they are dead.

# Type of change:
* Bug fix (Non-breaking change which fixes a bug)

# Checklist:
* Have you merged main into your branch?
* Have you tested your changes to ensure it works as expected and does not break existing functionality?
* If applicable, please ensure sufficient tests are added that is related to the changes.
* Please ensure this PR has a `label`, is linked to an `issue` and is related to a `project`
* If new documentation is required for this change, have you created a new documentation issue that describes the documentation needed?

### CODE REVIEW

**Review by ateagit — APPROVED** [review]
LGTM

**Review by reeved — APPROVED** [review]
LGTM

File: frontend/src/Pages/GameOverPage.jsx [hunk 1]
```diff
@@ -20,11 +20,13 @@ const GameOverPage = () => {
     });
 
     return (
-        <div> 
+        <div>
             <animated.div style={props}>
-                <Grid container direction='row' alignItems='center' justifyItems='center'>
+                <Grid container direction="row" alignItems="center" justifyItems="center">
```
Comment (parfei) [inline frontend/src/Pages/GameOverPage.jsx:25]: I thought we were using single quotes

**Review by parfei — APPROVED** [review]
