### PR TITLE
Fix gameover page styling

### LINKED ISSUE #193: Frontend comprehensive styling
**What are the tasks that need to be done?**
- [x] Home page
- [x] Lobby
- [x] Entry screen
- [x] Settings
- [x] Game Environment
- [x] Game over screen

### In-Depth Feature Description
Make styling for all screens and components the same for a more comprehensive game design.
Using Helvetica font and this colour palette:
161300372_262167702038549_5597630572452014120_n
#3E5B7F           #98C1D9          #E3F1F1          #293241          #EE6644

### Images for Reference:
Screen_Shot_2021-03-19_at_3 08 14_PM
Screen_Shot_2021-03-19_at_3 08 25_PM
Screen_Shot_2021-03-19_at_3 08 41_PM
Screen_Shot_2021-03-19_at_3 09 05_PM
Screen_Shot_2021-03-19_at_3 08 54_PM

### Feature Approval:
- [x]  Feature approved by: @SiyuQian

### PR DESCRIPTION
**Pull request by Dhors**
# Description
This PR fixes #193

Added styling changes of GameOver screen to bugfix of settings button on gameover screen. (the merge removed the styling changes)

# Demo
image

# Type of change:
* New feature (Non-breaking change that adds functionality)
* Bug fix (Non-breaking change which fixes a bug)

# Checklist:
* Have you merged main into your branch?
* Have you tested your changes to ensure it works as expected and does not break existing functionality?
* If applicable, please ensure sufficient tests are added that is related to the changes.
* Please ensure this PR has a `label`, is linked to an `issue` and is related to a `project`
* If new documentation is required for this change, have you created a new documentation issue that describes the documentation needed?

### CODE REVIEW

**Comment by reeved** [comment]
Hi Daniel,

Could you please add the Capitalize text transform to the Header selector in the TopBarSettings css file? Thanks! Everything else looks good :)

File: frontend/src/Hooks/useGameState.js [hunk 1]
```diff
@@ -315,7 +312,7 @@ export default function useGameState() {
             dispatch({
                 type: 'trial-end',
                 status:
-                    playerKilled === 'abstainVote' || !playerKilled
+                    playerKilled === 'abstain Vote' || !playerKilled
```
Comment (parfei) [inline frontend/src/Hooks/useGameState.js:315]: Made an issue to make this an enum: https://github.com/Mafia-Hands/Mafia/issues/230

**Review by ateagit — APPROVED** [review]
LGTM

**Review by parfei — APPROVED** [review]
